---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	query_understander(query_understander)
	retrieval_router(retrieval_router)
	searcher(searcher)
	evaluator(evaluator)
	reranker(reranker)
	reporter(reporter)
	__end__([<p>__end__</p>]):::last
	__start__ --> query_understander;
	evaluator -.-> reporter;
	evaluator -.-> reranker;
	evaluator -.-> retrieval_router;
	query_understander -.-> reporter;
	query_understander -.-> retrieval_router;
	reranker --> reporter;
	retrieval_router --> searcher;
	searcher -.-> evaluator;
	searcher -.-> reporter;
	reporter --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
